spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/movies2u
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
      format_sql: true